### PR TITLE
DataTemplateSelector

### PR DESCRIPTION
**Pull request by predalpha**
DataTemplateSelector implementation

### CODE REVIEW

**Review by predalpha — COMMENTED** [review]
Carefull, only 2 files need to be updated
RepeatableStack.cs 
RepeatableWrapLayout.cs 
[Not tested on IOS]

**Comment by muak** [comment]
@predalpha 
Because there were some unrelated files, I have merged this PR manually.
Thank you so much for the addition of function!

**Comment by predalpha** [comment]
You re welcome, i enjoy your controls which are essentials for my App !
If i got ideas for add-ons, ill keep in touch with you.

**Comment by muak** [comment]
@predalpha 
I'm looking forword to that time!
Best regards.

**Pull request closed without merging**
